services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    container_name: workout-tracker
    network_mode: host # для проброса впн в контейнер
    build: .
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./bot:/app/bot

  migrations:
    container_name: migrations
    environment:
      - DB__URL=${DB_URL_INTERNAL}
    build: .
    command: uv run alembic upgrade head
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./bot:/app/bot
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      db:
        condition: service_healthy

  seed:
    container_name: seed
    build: .
    command: uv run -m bot.data.seed
    volumes:
      - ./settings.toml:/app/settings.toml
      - ./bot:/app/bot
    environment:
      - DB__URL=${DB_URL_INTERNAL}
    depends_on:
      migrations:
        condition: service_completed_successfully

volumes:
  postgres_data:
