[bot]
token = "1234567890:AaBbCcDdEeFfGrOoShAHhIiJjKkLlMmNnOo"

[db]
url = "postgresql+asyncpg://tracker:workout_tracker@db:5432/workout_tracker"
# такой вариант будет работать только на сервере, локально нужно использовать localhost:5430

[logs]
project_name = "workout_tracker"
show_datetime = true
datetime_format = "%Y-%m-%d %H:%M:%S"
show_debug_logs = false
time_in_utc = false
use_colors_in_console = true
renderer = "console"  # "console" or "json"
allow_third_party_logs = true
