"""add user_id to muscles

Revision ID: 363413e23063
Revises: 9496e70710d0
Create Date: 2026-05-09 13:39:16.867012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363413e23063'
down_revision: Union[str, Sequence[str], None] = '9496e70710d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscles', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'muscles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'muscles', type_='foreignkey')
    op.drop_column('muscles', 'user_id')
    # ### end Alembic commands ###
