"""cascade delete exercise_muscles

Revision ID: 9496e70710d0
Revises: 8837f7bc6a38
Create Date: 2026-05-09 13:11:00.424151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9496e70710d0'
down_revision: Union[str, Sequence[str], None] = '8837f7bc6a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercise_muscles_exercise_id_fkey'), 'exercise_muscles', type_='foreignkey')
    op.drop_constraint(op.f('exercise_muscles_muscle_id_fkey'), 'exercise_muscles', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_muscles', 'muscles', ['muscle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise_muscles', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_muscles', type_='foreignkey')
    op.drop_constraint(None, 'exercise_muscles', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_muscles_muscle_id_fkey'), 'exercise_muscles', 'muscles', ['muscle_id'], ['id'])
    op.create_foreign_key(op.f('exercise_muscles_exercise_id_fkey'), 'exercise_muscles', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###
